import type { Metadata } from "next";
import Header from "@components/Header";
// フォントの読み取り
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// fontの定義を参考にしみよう↓↓

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body> */}
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
